// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI-only (migrate/db/studio). The schema engine cannot run through
    // Supabase's transaction pooler (6543), so prefer the session-mode
    // DIRECT_URL here. lib/db.ts keeps using DATABASE_URL at runtime.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
